spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:sqlite:file:/tmp/allohub.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
