-- =============================================================================
-- Legacy DDL — MariaDB/MySQL 호환 Mock (로컬 JDBC 미연결·H2/MariaDB 데모용)
-- Oracle 실제 DDL은 schema.oracle.sql 참고
-- MariaDB CREATE TABLE: https://mariadb.com/kb/en/create-table/
-- =============================================================================

CREATE TABLE IF NOT EXISTS TB_WAREHOUSE_IO_SCREEN (
    WAREHOUSE_IO_ID    BIGINT        NOT NULL AUTO_INCREMENT,
    WAREHOUSE_NAME     VARCHAR(100)  NOT NULL DEFAULT '',
    PRODUCT_CODE       VARCHAR(40)   NOT NULL DEFAULT '',
    PRODUCT_NAME       VARCHAR(100)  NOT NULL DEFAULT '',
    PRODUCT_CATEGORY   VARCHAR(60)   NOT NULL DEFAULT '',
    IN_QTY             INT           NOT NULL DEFAULT 0,
    OUT_QTY            INT           NOT NULL DEFAULT 0,
    CURRENT_STOCK      INT           NOT NULL DEFAULT 0,
    CLIENT_NAME        VARCHAR(100)  NOT NULL DEFAULT '',
    MANAGER_NAME       VARCHAR(60)   NOT NULL DEFAULT '',
    MANAGER_PHONE      VARCHAR(30)   NOT NULL DEFAULT '',
    IO_DATE            VARCHAR(20)   NOT NULL DEFAULT '',
    STATUS             VARCHAR(30)   NOT NULL DEFAULT 'DRAFT',
    MEMO               VARCHAR(500)  NOT NULL DEFAULT '',
    DELETED_YN         CHAR(1)       NOT NULL DEFAULT 'N',
    UPDATED_AT         TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_WAREHOUSE_IO_SCREEN PRIMARY KEY (WAREHOUSE_IO_ID),
    CONSTRAINT CK_WIO_SCREEN_DELETED CHECK (DELETED_YN IN ('Y', 'N'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX IF NOT EXISTS IDX_WIO_ACTIVE ON TB_WAREHOUSE_IO_SCREEN (DELETED_YN, WAREHOUSE_IO_ID DESC);
CREATE INDEX IF NOT EXISTS IDX_WIO_UPDATED_AT ON TB_WAREHOUSE_IO_SCREEN (UPDATED_AT, WAREHOUSE_IO_ID);
