package com.briefly.common.listener;

import com.briefly.common.util.DBConnectionUtil;
import jakarta.servlet.ServletContextEvent;
import jakarta.servlet.ServletContextListener;
import jakarta.servlet.annotation.WebListener;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * DB에 필요한 테이블이 없으면 애플리케이션 시작 시 생성한다.
 * H2 in-memory(db.properties 기본값)는 컨테이너가 재시작될 때마다 데이터가
 * 초기화되므로, 매 시작마다 스키마를 다시 만들고 샘플 데이터를 채워
 * "SELECT * FROM funds" 같은 조회가 항상 성공하도록 보장한다.
 * 운영 DB(Postgres 등, db-prod.properties)를 쓰는 경우에도 CREATE TABLE IF
 * NOT EXISTS라 기존 스키마/데이터를 건드리지 않는다.
 */
@WebListener
public class DbInitListener implements ServletContextListener {
    private static final Logger LOG = Logger.getLogger(DbInitListener.class.getName());

    private static final String[] DDL = {
        """
        CREATE TABLE IF NOT EXISTS users (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            email VARCHAR(255) NOT NULL UNIQUE,
            password_hash VARCHAR(255) NOT NULL,
            name VARCHAR(100) NOT NULL,
            role VARCHAR(20) NOT NULL DEFAULT 'USER',
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS funds (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR(200) NOT NULL,
            description VARCHAR(2000),
            risk_grade INT NOT NULL,
            expected_return DECIMAL(6,2),
            status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS fund_applications (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id BIGINT NOT NULL,
            fund_id BIGINT NOT NULL,
            amount DECIMAL(15,2) NOT NULL,
            status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS watchlists (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id BIGINT NOT NULL,
            fund_id BIGINT NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS risk_alerts (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            fund_id BIGINT NOT NULL,
            title VARCHAR(200) NOT NULL,
            message VARCHAR(2000),
            previous_grade INT,
            new_grade INT,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS fund_reports (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            fund_id BIGINT NOT NULL,
            title VARCHAR(200) NOT NULL,
            content VARCHAR(4000),
            report_date DATE NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """,
    };

    private static final String SEED_FUNDS = """
        INSERT INTO funds (name, description, risk_grade, expected_return, status)
        SELECT * FROM (VALUES
            ('글로벌 성장주 펀드', '해외 대형 기술주 중심의 성장형 펀드입니다.', 3, 7.50, 'ACTIVE'),
            ('국내 배당주 펀드', '안정적인 배당 수익을 추구하는 국내 주식형 펀드입니다.', 2, 4.20, 'ACTIVE'),
            ('채권혼합형 펀드', '국공채와 우량 회사채에 분산 투자하는 안정형 펀드입니다.', 1, 3.10, 'ACTIVE'),
            ('신흥국 주식형 펀드', '아시아·남미 신흥시장에 투자하는 고위험 고수익 펀드입니다.', 5, 11.30, 'ACTIVE')
        ) AS seed(name, description, risk_grade, expected_return, status)
        WHERE NOT EXISTS (SELECT 1 FROM funds)
        """;

    @Override
    public void contextInitialized(ServletContextEvent sce) {
        try (Connection conn = DBConnectionUtil.getConnection();
             Statement stmt = conn.createStatement()) {
            for (String ddl : DDL) {
                stmt.execute(ddl);
            }
            stmt.executeUpdate(SEED_FUNDS);
            LOG.info("DbInitListener: 스키마 확인/생성 및 샘플 데이터 시딩 완료");
        } catch (SQLException e) {
            LOG.log(Level.SEVERE, "DbInitListener: 스키마 초기화 실패", e);
        }
    }

    @Override
    public void contextDestroyed(ServletContextEvent sce) {
        // no-op
    }
}
