server:
  port: 8080
  servlet:
    context-path: ${SERVER_SERVLET_CONTEXT_PATH:}
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: backend
  jpa:
    open-in-view: false
