package com.allochub.global.exception;

public enum ErrorCode {
    INVALID_INPUT,
    INVALID_ALLOCATION_RATIO,
    INVALID_INVESTMENT_AMOUNT,
    RECONCILIATION_FAILED,
    DISTRIBUTION_RECONCILIATION_FAILED,
    DUPLICATE,
    UNAUTHORIZED,
    FORBIDDEN,
    INTERNAL_SERVER_ERROR
}
