-- =============================================================================
-- 파티션 테이블 예시 — Oracle (참고용, PoC schema.sql 과 별도)
-- 문서: ../PARTITIONING_GUIDE.md
-- Concepts: https://docs.oracle.com/en/database/oracle/oracle-database/19/cncpt/partitioning.html
-- =============================================================================

-- DROP TABLE tb_warehouse_io_part PURGE;

CREATE TABLE tb_warehouse_io_part (
    warehouse_io_id   NUMBER(19)       GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    warehouse_name    VARCHAR2(100)    DEFAULT '' NOT NULL,
    product_code      VARCHAR2(40)     DEFAULT '' NOT NULL,
    product_name      VARCHAR2(100)    DEFAULT '' NOT NULL,
    product_category  VARCHAR2(60)     DEFAULT '' NOT NULL,
    in_qty            NUMBER(10)       DEFAULT 0 NOT NULL,
    out_qty           NUMBER(10)       DEFAULT 0 NOT NULL,
    current_stock     NUMBER(10)       DEFAULT 0 NOT NULL,
    client_name       VARCHAR2(100)    DEFAULT '' NOT NULL,
    status            VARCHAR2(30)     DEFAULT 'DRAFT' NOT NULL,
    deleted_yn        CHAR(1)          DEFAULT 'N' NOT NULL,
    stock_date        DATE             NOT NULL,
    created_at        TIMESTAMP(6)     DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at        TIMESTAMP(6)     DEFAULT SYSTIMESTAMP NOT NULL,
    deleted_at        TIMESTAMP(6)     NULL,
    source_system     VARCHAR2(50)     DEFAULT 'refactor-api' NOT NULL,
    etl_batch_id      VARCHAR2(50)     NULL,
    CONSTRAINT pk_tb_warehouse_io_part PRIMARY KEY (created_at, warehouse_io_id),
    CONSTRAINT ck_tb_warehouse_io_part_deleted CHECK (deleted_yn IN ('Y', 'N'))
)
PARTITION BY RANGE (created_at) (
    PARTITION p2026_06 VALUES LESS THAN (TIMESTAMP '2026-07-01 00:00:00'),
    PARTITION p2026_07 VALUES LESS THAN (TIMESTAMP '2026-08-01 00:00:00'),
    PARTITION p_future  VALUES LESS THAN (MAXVALUE)
);

CREATE INDEX idx_wh_part_updated ON tb_warehouse_io_part (updated_at, warehouse_io_id) LOCAL;

-- INTERVAL 월별 자동 파티션 (운영 시 검토)
-- PARTITION BY RANGE (created_at)
-- INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
-- ( PARTITION p_start VALUES LESS THAN (TIMESTAMP '2026-07-01 00:00:00') );
