-- =============================================================================
-- Refactor DDL — Oracle Database
-- CREATE INDEX: https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/CREATE-INDEX.html
-- 변경 추적: ../CHANGE_TRACKING_GUIDE.md
-- 파티셔닝(확장 시): ../PARTITIONING_GUIDE.md · partition-example.sql
-- View/요약(리포트): ../VIEW_SUMMARY_GUIDE.md · summary-views-example.sql
-- =============================================================================

CREATE TABLE tb_warehouse_io (
    warehouse_io_id   NUMBER(19)       GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    warehouse_name    VARCHAR2(100)    DEFAULT '' NOT NULL,
    product_code      VARCHAR2(40)     DEFAULT '' NOT NULL,
    product_name      VARCHAR2(100)    DEFAULT '' NOT NULL,
    product_category  VARCHAR2(60)     DEFAULT '' NOT NULL,
    in_qty            NUMBER(10)       DEFAULT 0 NOT NULL,
    out_qty           NUMBER(10)       DEFAULT 0 NOT NULL,
    current_stock     NUMBER(10)       DEFAULT 0 NOT NULL,
    client_name       VARCHAR2(100)    DEFAULT '' NOT NULL,
    status            VARCHAR2(30)     DEFAULT 'DRAFT' NOT NULL,
    deleted_yn        CHAR(1)          DEFAULT 'N' NOT NULL,
    created_at        TIMESTAMP(6)     DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at        TIMESTAMP(6)     DEFAULT SYSTIMESTAMP NOT NULL,
    deleted_at        TIMESTAMP(6)     NULL,
    source_system     VARCHAR2(50)     DEFAULT 'refactor-api' NOT NULL,
    etl_batch_id      VARCHAR2(50)     NULL,
    CONSTRAINT pk_tb_warehouse_io PRIMARY KEY (warehouse_io_id),
    CONSTRAINT ck_tb_warehouse_io_deleted CHECK (deleted_yn IN ('Y', 'N'))
);

CREATE TABLE tb_investor (
    investor_id         NUMBER(19)     GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    investor_name       VARCHAR2(100)  NOT NULL,
    investor_grade      VARCHAR2(20)   DEFAULT '' NOT NULL,
    total_amount        NUMBER(19)     DEFAULT 0 NOT NULL,
    last_product_name   VARCHAR2(100)  DEFAULT '' NOT NULL,
    screen_memo         VARCHAR2(500)  DEFAULT '' NOT NULL,
    created_at          TIMESTAMP(6)   DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at          TIMESTAMP(6)   DEFAULT SYSTIMESTAMP NOT NULL,
    deleted_at          TIMESTAMP(6)   NULL,
    source_system       VARCHAR2(50)   DEFAULT 'refactor-api' NOT NULL,
    etl_batch_id        VARCHAR2(50)   NULL,
    CONSTRAINT pk_tb_investor PRIMARY KEY (investor_id)
);

CREATE INDEX idx_warehouse_active ON tb_warehouse_io (deleted_yn, warehouse_io_id DESC);
CREATE INDEX idx_warehouse_updated_at ON tb_warehouse_io (updated_at, warehouse_io_id);
CREATE INDEX idx_investor_name ON tb_investor (investor_name);
CREATE INDEX idx_investor_updated_at ON tb_investor (updated_at, investor_id);
